import { Fragment } from "react";
import { usePageTitle } from "@/hooks/usePageTitle";
import { LegalLayout } from "./LegalLayout";

const sections = [
  {
    title: "Information we collect",
    paragraphs: [
      "We collect only the data required to deliver personalised introductions, premium hospitality experiences, and a secure member community.",
      "This includes the details you share during onboarding, preferences you set in your profile, and engagement signals generated as you explore Connective experiences.",
    ],
    listTitle: "Data types",
    listItems: [
      "Identity data such as your name, role, and professional affiliations.",
      "Preference data used to tailor invites, including interests and availability windows.",
      "Technical data generated by your devices, including IP address, browser type, and session duration.",
    ],
  },
  {
    title: "How we use your information",
    paragraphs: [
      "Every data point powers more thoughtful matches, safer in-person events, and richer community interactions. We never sell member information.",
    ],
    listTitle: "We use data to",
    listItems: [
      "Curate event line-ups and invitation lists with respect for your preferences.",
      "Deliver concierge support, confirmations, and program updates in real time.",
      "Improve Connective's digital platforms and verify member safety.",
    ],
  },
  {
    title: "Sharing and legal bases",
    paragraphs: [
      "We share data only with trusted vendors (such as payment processors, event hosts, and security partners) who are bound by data protection agreements and may use it solely to support Connective services.",
      "Processing is grounded in legitimate interest to operate our community, performance of our agreement with you, and compliance with legal obligations. Where required, we rely on your consent for optional features.",
    ],
  },
  {
    title: "Cookies and analytics",
    paragraphs: [
      "We use cookies and similar technologies to keep you signed in, remember preferences, and understand how members engage with programming.",
    ],
    listTitle: "Your choices",
    listItems: [
      "Manage browser settings to block or delete non-essential cookies.",
      "Adjust in-product preferences where available to opt out of certain analytics events.",
      "Contact privacy@connective.app if you want more detail on the tools we use.",
    ],
  },
  {
    title: "Data retention and security",
    paragraphs: [
      "We retain data only for as long as needed to provide services, comply with law, or resolve disputes. Once data is no longer required, we archive or delete it securely.",
      "Our controls include encryption in transit, restricted access to production systems, and continuous monitoring for unusual activity.",
    ],
  },
  {
    title: "Your privacy controls",
    paragraphs: [
      "You are in command of the story you share. Update profile data, adjust matching settings, or request data deletion from your dashboard or by contacting the concierge team.",
      "For formal requests, email privacy@connective.app and our compliance team will respond within 72 hours.",
    ],
    listTitle: "You can request",
    listItems: [
      "Access to, correction of, or deletion of your personal data.",
      "Export of your data in a portable format, where technically feasible.",
      "Restriction of certain processing where permitted by law.",
    ],
  },
  {
    title: "International transfers",
    paragraphs: [
      "If we transfer data outside your home jurisdiction, we use recognised safeguards such as standard contractual clauses to protect it.",
      "You can contact privacy@connective.app for a copy of the relevant safeguards or to ask questions about how your data moves across regions.",
    ],
  },
];

const Privacy = () => {
  usePageTitle("Privacy Policy");

  return (
    <LegalLayout
      title="Privacy Policy"
      description="Transparency is the foundation of trust. This policy explains how Connective collects, uses, and protects your information."
      lastUpdated="January 2025"
    >
      {sections.map((section) => (
        <section key={section.title} className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">{section.title}</h2>
          {section.paragraphs.map((paragraph) => (
            <p key={paragraph}>{paragraph}</p>
          ))}
          {section.listItems && section.listTitle && (
            <Fragment>
              <p className="font-medium text-foreground/80">{section.listTitle}</p>
              <ul className="list-disc space-y-2 pl-5">
                {section.listItems.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </Fragment>
          )}
        </section>
      ))}
      <section className="rounded-2xl border border-white/10 bg-card/60 p-6 text-sm shadow-[0_20px_45px_-25px_rgba(17,24,39,0.55)]">
        <h2 className="text-lg font-semibold text-foreground">Questions?</h2>
        <p className="mt-3">
          Connective's privacy team is available at <a className="underline" href="mailto:privacy@connective.app">privacy@connective.app</a>.
          We will confirm receipt of your request and outline next steps promptly.
        </p>
      </section>
    </LegalLayout>
  );
};

export default Privacy;
