-- Ensure admin_audit_log exists for tracking privileged actions
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  target_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.admin_audit_log IS 'Tracks actions performed by administrators for security and compliance.';
COMMENT ON COLUMN public.admin_audit_log.admin_id IS 'The user ID of the admin who performed the action.';
COMMENT ON COLUMN public.admin_audit_log.action IS 'A description of the action performed.';
COMMENT ON COLUMN public.admin_audit_log.target_user_id IS 'The user ID of the user who was the target of the action, if applicable.';
COMMENT ON COLUMN public.admin_audit_log.metadata IS 'Optional structured context about the action (e.g., payload summary, IP address).';
COMMENT ON COLUMN public.admin_audit_log.created_at IS 'The timestamp of when the action was performed.';

-- Enable RLS and enforce least privilege
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- Admins can write audit entries for their actions
DROP POLICY IF EXISTS "Allow admins to insert audit logs" ON public.admin_audit_log;
CREATE POLICY "Allow admins to insert audit logs"
  ON public.admin_audit_log
  FOR INSERT
  WITH CHECK (public.is_admin(auth.uid()));

-- Admins can read the audit trail
DROP POLICY IF EXISTS "Allow admins to view audit logs" ON public.admin_audit_log;
CREATE POLICY "Allow admins to view audit logs"
  ON public.admin_audit_log
  FOR SELECT
  USING (public.is_admin(auth.uid()));

-- Prevent modifications or deletions of audit records
DROP POLICY IF EXISTS "Disallow updates to audit logs" ON public.admin_audit_log;
CREATE POLICY "Disallow updates to audit logs"
  ON public.admin_audit_log
  FOR UPDATE
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS "Disallow deletions of audit logs" ON public.admin_audit_log;
CREATE POLICY "Disallow deletions of audit logs"
  ON public.admin_audit_log
  FOR DELETE
  USING (false);
