-- Create user_roles table
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, role)
);

-- Add comments for documentation
COMMENT ON TABLE public.user_roles IS 'Stores user roles, separate from profiles for security.';
COMMENT ON COLUMN public.user_roles.user_id IS 'Foreign key to auth.users.id';
COMMENT ON COLUMN public.user_roles.role IS 'The role of the user (e.g., admin, user).';

-- Enable RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
