-- Create admin_audit_log table
CREATE TABLE public.admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  target_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for documentation
COMMENT ON TABLE public.admin_audit_log IS 'Tracks actions performed by administrators for security and compliance.';
COMMENT ON COLUMN public.admin_audit_log.admin_id IS 'The user ID of the admin who performed the action.';
COMMENT ON COLUMN public.admin_audit_log.action IS 'A description of the action performed.';
COMMENT ON COLUMN public.admin_audit_log.target_user_id IS 'The user ID of the user who was the target of the action, if applicable.';
COMMENT ON COLUMN public.admin_audit_log.created_at IS 'The timestamp of when the action was performed.';

-- Enable RLS
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- 1. Admins can view all audit logs
-- 1. Admins can insert new audit logs
CREATE POLICY "Allow admins to insert audit logs"
ON public.admin_audit_log
FOR INSERT
WITH CHECK (public.is_admin(auth.uid()));

-- 2. Admins can view all audit logs
CREATE POLICY "Allow admins to view audit logs"
ON public.admin_audit_log
FOR SELECT
USING (public.is_admin(auth.uid()));

-- 2. Prevent updates to audit logs
CREATE POLICY "Disallow updates to audit logs"
ON public.admin_audit_log
FOR UPDATE
USING (false);

-- 3. Prevent deletions of audit logs
CREATE POLICY "Disallow deletions of audit logs"
ON public.admin_audit_log
FOR DELETE
USING (false);
