// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_SITE_URL = import.meta.env.VITE_SUPABASE_SITE_URL;

export const isSupabaseConfigured = Boolean(
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY,
);

const createNotConfiguredError = () =>
  new Error(
    "Supabase environment variables are not configured. Live data features are disabled in this preview.",
  );

const createStubQueryBuilder = () => {
  const error = createNotConfiguredError();
  const result = Promise.resolve({ data: null, error });

  const builder: Record<string, (...args: unknown[]) => unknown> & {
    maybeSingle: () => Promise<{ data: null; error: Error }>;
    single: () => Promise<{ data: null; error: Error }>;
  } = {
    select: () => builder,
    insert: () => builder,
    update: () => builder,
    upsert: () => builder,
    eq: () => builder,
    order: () => builder,
    limit: () => builder,
    maybeSingle: () => result,
    single: () => result,
  };

  return builder;
};

const resolveSiteUrl = () => {
  if (SUPABASE_SITE_URL) {
    try {
      return new URL(SUPABASE_SITE_URL).toString();
    } catch (error) {
      console.warn("supabase:invalid-site-url", error);
    }
  }

  if (typeof window !== "undefined" && window.location?.origin) {
    return window.location.origin;
  }

  return "http://localhost";
};

export const getSupabaseRedirectUrl = (path: string) => {
  const base = resolveSiteUrl();
  try {
    return new URL(path, `${base.replace(/\/$/, "")}/`).toString();
  } catch (error) {
    console.warn("supabase:invalid-redirect-path", error);
    return `${base.replace(/\/$/, "")}/${path.replace(/^\//, "")}`;
  }
};

const createStubClient = (): SupabaseClient<Database> => {
  const error = createNotConfiguredError();
  const subscription = { unsubscribe: () => {} };
  const builder = createStubQueryBuilder();

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error }),
      getUser: async () => ({ data: { user: null }, error }),
      onAuthStateChange: () => ({
        data: { subscription },
        error: null,
      }),
      signInWithPassword: async () => ({
        data: { user: null, session: null },
        error,
      }),
      signInWithOAuth: async () => {
        throw error;
      },
      exchangeCodeForSession: async () => ({
        data: { session: null, user: null },
        error,
      }),
      signOut: async () => ({ error }),
    },
    from: () => builder,
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: "pkce",
      },
    })
  : createStubClient();
